title: Md Habibur Rahman
description: Materials + AI for Photovoltaics
url: https://msehabibur.github.io
theme: minima
minima:
  skin: classic
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 2..3
plugins: []   # keep empty so GH Pages builds without custom plugins
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - scripts
